[platformio]
default_envs = f411_recovery_boot

[env:f411_recovery_boot]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = stlink
board_upload.maximum_size = 16384
build_flags =
    -Iinclude
    -DSTM32F411xE
    -DUSE_HAL_DRIVER
    -DUSBCON
    -DUSBD_USE_CDC
    -DUSBD_USER_REGISTER_CALLBACK=0
    -DAPP_BASE=0x08004000UL
    -DAPP_LIMIT=0x08060000UL
    -DMANIFEST_BASE=0x08060000UL
    -DMANIFEST_LIMIT=0x08064000UL
    -DSYSTEM_MEMORY=0x1FFF0000UL
    -DBOOT_REQUEST_MAGIC=0x42465544UL
    -Os
    -flto
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Wl,--print-memory-usage

build_src_flags =
    -Wall
    -Wextra
    -Werror
    -Wshadow
    -Wundef
